name: author-app

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - author-app

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - author-app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - author-app
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mongo_data:

networks:
  author-app:
    driver: bridge
